"""empty message

Revision ID: 969d7d7ae501
Revises: eb9cbbf83ed2
Create Date: 2025-10-22 16:04:07.082276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969d7d7ae501'
down_revision = 'eb9cbbf83ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('media_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('media_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
