"""empty message

Revision ID: eb9cbbf83ed2
Revises: ad84b9fec8c2
Create Date: 2025-10-22 15:50:10.846767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb9cbbf83ed2'
down_revision = 'ad84b9fec8c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('comment_text',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('media_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('type')
        batch_op.drop_column('url')
        batch_op.drop_column('post_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('caption')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.alter_column('lastname',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('firstname',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption', sa.VARCHAR(length=2200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type', postgresql.ENUM('IMAGE', 'VIDEO', name='mediatype'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('media_post_id_fkey', 'post', ['post_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.alter_column('comment_text',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
